export enum ActionType {
  ADD_EVENT = "ADD_EVENT",
  REMOVE_EVENT = "REMOVE_EVENT",
  UPDATE_EVENT = "UPDATE_EVENT",
  ADD_PROGRESS_TRACK = "ADD_PROGRESS_TRACK",
  UPDATE_PROGRESS_TRACK = "UPDATE_PROGRESS_TRACK"
}
